### ISSUE TITLE
Security Error on unit tests using onlyFromAutocomplete

### ISSUE THREAD

**Issue by Rataah** [Gbuomprisco/ngx-chips#570]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question
```

**Current behavior**

Using the attribute **[onlyFromAutocomplete]="true"** raise a security error during unit tests.

```
Failed: Template parse errors:        Binding to event property 'onlyFromAutocomplete' is disallowed for security reasons, please use (lyFromAutocomplete)=...        
If 'onlyFromAutocomplete' is a directive input, make sure the directive is imported by the current module. ("
              [placeholder]="'Filter by area'"
              [secondaryPlaceholder]="'Filter by area'"
              [ERROR ->][onlyFromAutocomplete]="true">
              <tag-input-dropdown [showDropdownIfEmpty]="true" [autocomplet"): ng:///DynamicTestModule/MappingComponent.html@11:6        
parse@http://localhost:9876/_karma_webpack_/vendor.bundle.js:84997:80        
_compileTemplate@http://localhost:9876/_karma_webpack_/vendor.bundle.js:99149:44
```
We tried with the syntax **onlyFromAutocomplete="{{true}}"**, a security error is still raised

--

**Expected behavior**
No security error

**What do you use to build your app?. Please specify the version**
angular-cli (1.3.2)

**Angular version:** 
4.4.3

**ngx-chips version:**
1.5.3

**Browser:**
Karma (1.7.1) with PhantomJS (4.0.5) powered by Chrome

**Comment by seanmt13** [comment]
I am also experience this issue is this caused by not importing it properly?

**Comment by seanmt13** [comment]
Actually what i found that caused my issue was that i put [onlyFromAutocomplete] on the wrong tag. it needs to be on the <tag-input> tag.

**Comment by Gbuomprisco** [comment]
Hi @Rataah, can you paste your code?

**Comment by WaleedAli007** [comment]
Facing similar issue. Is this the problem with importing module?

**Comment by pramod9254** [comment]
I am also facing the same issue
My code is:
<tag-input [ngModel]="['@item']"
      [onlyFromAutocomplete]="true">
<tag-input-dropdown [showDropdownIfEmpty]="true"
                   [autocompleteItems]="['iTem1', 'item2', 'item3']">
</tag-input-dropdown>
</tag-input>

Error:
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Binding to event property 'onlyFromAutocomplete' is disallowed for security reasons, please use (lyFromAutocomplete)=...
If 'onlyFromAutocomplete' is a directive input, make sure the directive is imported by the current module. ("

        <tag-input [ngModel]="['@item']"
      [ERROR ->][onlyFromAutocomplete]="true">
<tag-input-dropdown [showDropdownIfEmpty]="true"
                   [a"): ng:///TaskModule/TaskComponent.html@26:6
Can't bind to 'onlyFromAutocomplete' since it isn't a known property of 'tag-input'.
1. If 'tag-input' is an Angular component and it has 'onlyFromAutocomplete' input, then verify that it is part of this module.
2. If 'tag-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

        <tag-input [ngModel]="['@item']"
      [ERROR ->][onlyFromAutocomplete]="true">
....

**Comment by yangjiel** [comment]
I am facing this error as well on my unit test. Any solution?

**Comment by yangjiel** [comment]
Okay I am dumb, I forgot to import 
```
TagInputModule, 
BrowserAnimationsModule,
FormsModule,
ReactiveFormsModule
```
in my test.

**Comment by tndungu** [comment]
Removed the prefix 'on' to remain with 'lyFromAutocomplete'
