### ISSUE TITLE
 Can't bind to 'ngModel' since it isn't a known property of 'tag-input'.

### ISSUE THREAD

**Issue by marcusbrady1** [Gbuomprisco/ngx-chips#613]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

when I run the app through the angular CLI I get "Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'tag-input'."

**Expected behavior**

the app would work and hopefully I would have a tags component that worked too

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular cli

**Angular version:** 

5

[Archive.zip](https://github.com/Gbuomprisco/ngx-chips/files/1476893/Archive.zip)

**ngx-chips version:**

1.5.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome

**Comment by Gbuomprisco** [comment]
Hi Marcus, 

I don't know if the file you posted is actually your code (by this I mean if you pasted part of it or all of it. I would guess it's not as that would not compile. 

```javascript
@NgModule({
  imports: [ CommonModule, FormsModule, ReactiveFormsModule, TagInputModule, BrowserAnimationsModule ]
})
```

You need to export a class for your module, and then bootstrap this module. Otherwise, it looks all correct in terms of modules imported. Can you clarify the above? In case can you push a repository so that I can look at it?

**Comment by geekscorner** [comment]
I had the same problem. The readme doesn't explicitly state which imports are needed for this library to function properly. (except BrowserAnimationModule).  But you need at least FormsModule if you want ngModel to work at all.  Probably should say this.

**Comment by sactyagi** [comment]
Facing the same issue and I have imported FormsModule and BrowserModule but still getting the same error. Also I have implemented the below 3 schema option bur the erro ris also not supressed, any help please ?

Can't bind to 'ngModel' since it isn't a known property of 'tag-input'.
1. If 'tag-input' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'tag-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by Gbuomprisco** [comment]
Imported ReactiveFormsModule?

**Comment by sactyagi** [comment]
@Gbuomprisco  Thank you, but ReactiveFormsModule also imported.

**Comment by Gbuomprisco** [comment]
the issue is probably that you're not importing Taginpitmodule in the module you actually need it

**Comment by Gbuomprisco** [comment]
See https://github.com/Gbuomprisco/ngx-chips/issues/688

**Comment by sactyagi** [comment]
I already  have 
import { TagInputModule } from 'ngx-chips';
which is not working.
Should I use 
import {TagInputModule} from 'ng2-tag-input';

**Comment by Gbuomprisco** [comment]
Yes, but you need to import it in the right module, as you can read in the ticket i linked, the user was importing it in the wrong module. It's not enough to add it to the root module if you use it in another module, like lazy loaded routes.

**Comment by sactyagi** [comment]
@Gbuomprisco , this issue is coming while I am trying to run Karma to validate one of the component.
While running the application its working fine, but when running the spec file using Karma for the same its failing with the following error:
Failed: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'tag-input'.
1. If 'tag-input' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'tag-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      Name   
    </span>   
    <tag-input [ERROR ->][(ngModel)]='chipSource'  [lyFromAutocomplete]="true" theme='chip-theme' hideForm="0" (onRemove)="onC"): ng:///DynamicTestModule/PackageListPageComponent.html@5:15
Can't bind to 'lyFromAutocomplete' since it isn't a known property of 'tag-input'.

**Comment by Gbuomprisco** [comment]
I have no idea without reading the code, but the issue is within your project.
