### ISSUE TITLE
how to popluate data if we are using formControlname

### ISSUE THREAD

**Issue by ashokthrymr** [Gbuomprisco/ngx-chips#746]
**HTML**

```
 <form role="form" [formGroup]="form" >
 <tag-input formControlName="items" (onSelect)="onSelect($event)"></tag-input>
</form>
```

**in .ts file**
```
 this.form = this.formBuilder.group({
      items:new FormControl(''),
    });

```

**Comment by Gbuomprisco** [comment]
That should work but you need to initialise with an array. Check the demo in the repository. Please complete template next time, don't remove ir

**Comment by ashokthrymr** [comment]
Hi..**Gbuomprisco**  I am Providing Stackbliz code.Let me know where ever made wrong.

[https://stackblitz.com/edit/angular4-a9g1lb?file=app%2Fapp.component.html](Code)
1) I have two problems ,One is populating data using **formControlname**

2)When I am entering data in TagInput,previous value appening to next value

**Comment by Gbuomprisco** [comment]
Hi @ashokthrymr, a bunch of problems not related to the library I can see:
- you're using fromControlName instead of formControlName, notice the typo
- you're using formControlName without a FormGroup, and passing the items reference to it rather than the control name.
Maybe you may want to read the documentation, or see the code:
- form group: https://github.com/Gbuomprisco/ngx-chips/blob/master/demo/home/home.ts#L18
- template: https://github.com/Gbuomprisco/ngx-chips/blob/master/demo/home/home.html#L201

**Comment by ashokthrymr** [comment]
Thanks you @Gbuomprisco .It helps.
[https://stackblitz.com/edit/angular4-a9g1lb?file=app%2Fapp.component.ts](url)
Small help.....Open the Link check the output then you will know the issue better
from second value onwards not showing the value properly.when I click on those item then it's expanding

**Comment by Gbuomprisco** [comment]
The example uses Angular 4, but should use Angular 5 (or 6 with the latest version)

**Comment by ashokthrymr** [comment]
Thanks for your Support
